name = "pos-api"
main = "worker.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"
database_name = "pos-db"
database_id = "7073997b-8b46-4a84-bcdb-e0103c283d20"

# Setelah membuat database:
#   wrangler d1 create pos_multi_tenant
#   wrangler d1 execute pos_multi_tenant --file=./schema.sql
#   wrangler deploy
